Add the init command

diff --git a/bin/peach b/bin/peach
--- a/bin/peach
+++ b/bin/peach
@@ -105,6 +105,30 @@ function display_help {
     exit 1
 }
 
+# Prepare the peach setup...
+if [ "$1" == "init" ]; then
+    shift 1
+
+    # Check if the command is executed within a project directory where Peach is installed
+    if [ ! -d "./vendor/ysocode/peach" ]; then
+        echo "Error: The 'init' command must be executed in the project directory where Peach is installed."
+        exit 1
+    fi
+
+    # Copy the stub file during initialization
+    STUB_SOURCE="./vendor/ysocode/peach/stubs/docker-compose.stub"
+    STUB_DESTINATION="docker-compose.yml"
+    
+    if [ -f "$STUB_SOURCE" ]; then
+        cp "$STUB_SOURCE" "$STUB_DESTINATION"
+        echo "Peach setup complete."
+        exit
+    else
+        echo "Error: Peach setup failed. Please make sure you have installed the required dependencies."
+        exit 1
+    fi
+fi
+
 # Proxy the "help" command...
 if [ $# -gt 0 ]; then
     if [ "$1" == "help" ] || [ "$1" == "-h" ] || [ "$1" == "-help" ] || [ "$1" == "--help" ]; then
